 // <auto-generated />
using System;
using EvidencijaSastanka.Podaci.Kontekst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvidencijaSastanka.Podaci.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvidencijaSastanka.Modeli.Modeli.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("EvidencijaSastanka.Modeli.Modeli.PrisustvoNaSastanku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Prisutan")
                        .HasColumnType("bit");

                    b.Property<int>("SastanakId")
                        .HasColumnType("int");

                    b.Property<int>("StanarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SastanakId");

                    b.HasIndex("StanarId");

                    b.ToTable("PrisustvoNaSastanku");
                });

            modelBuilder.Entity("EvidencijaSastanka.Modeli.Modeli.Sastanak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojPrisutnih")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumSastanka")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProcenatPrisutnih")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StatusSastanka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zakljucak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZgradaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZgradaId");

                    b.ToTable("Sastanak");
                });

            modelBuilder.Entity("EvidencijaSastanka.Modeli.Modeli.Stanar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojStana")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZgradaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZgradaId");

                    b.ToTable("Stanar");
                });

            modelBuilder.Entity("EvidencijaSastanka.Modeli.Modeli.Zgrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zgrada");
                });

            modelBuilder.Entity("EvidencijaSastanka.Modeli.Modeli.PrisustvoNaSastanku", b =>
                {
                    b.HasOne("EvidencijaSastanka.Modeli.Modeli.Sastanak", "Sastanak")
                        .WithMany("Prisustva")
                        .HasForeignKey("SastanakId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EvidencijaSastanka.Modeli.Modeli.Stanar", "Stanar")
                        .WithMany()
                        .HasForeignKey("StanarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sastanak");

                    b.Navigation("Stanar");
                });

            modelBuilder.Entity("EvidencijaSastanka.Modeli.Modeli.Sastanak", b =>
                {
                    b.HasOne("EvidencijaSastanka.Modeli.Modeli.Zgrada", "Zgrada")
                        .WithMany("Sastanci")
                        .HasForeignKey("ZgradaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Zgrada");
                });

            modelBuilder.Entity("EvidencijaSastanka.Modeli.Modeli.Stanar", b =>
                {
                    b.HasOne("EvidencijaSastanka.Modeli.Modeli.Zgrada", "Zgrada")
                        .WithMany("Stanari")
                        .HasForeignKey("ZgradaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Zgrada");
                });

            modelBuilder.Entity("EvidencijaSastanka.Modeli.Modeli.Sastanak", b =>
                {
                    b.Navigation("Prisustva");
                });

            modelBuilder.Entity("EvidencijaSastanka.Modeli.Modeli.Zgrada", b =>
                {
                    b.Navigation("Sastanci");

                    b.Navigation("Stanari");
                });
#pragma warning restore 612, 618
        }
    }
}
